Controllers/BookController.cs
using Labrary2023.Data.Repository;
using Labrary2023.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Labrary2023.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        public readonly Reposotorybook _reBook;
        public readonly Reposotorybook_author _reBookAuthor;
        public readonly ReposotoryCategory _reCategory;
        public readonly Reposotory_author _reAuthoer;

        public BookController(Reposotorybook   reBook , ReposotoryCategory  reCategory , Reposotorybook_author reBookAuthor , Reposotory_author  reAuthoer)
        {
            _reAuthoer = reAuthoer;
            _reBook = reBook;
            _reBookAuthor = reBookAuthor;
            _reCategory=reCategory;
        }

        public IActionResult index()
        {
           
            return View();
        }



        [HttpGet]
        public ActionResult listbook()
        {
            IEnumerable<book> item = _reBook.list<book>()  ;
            return View(item);
        }  
        

        [HttpGet,HttpPost]
        public ActionResult DeleteBook(int id)
        {  
            _reBook.delete(_reBook.get<book>(id));
            return RedirectToAction("listbook");
        }

        [HttpGet]
        public ActionResult AddBook()
        {
            ViewBag.idcat = _reBook.category();
            return View();
        } 
        
        [HttpPost]
        public ActionResult AddBook(book obj)
        {
            if(ModelState.IsValid)
            {
                _reBook.add(obj);
                return RedirectToAction("listbook");
            }
            else
            {  
                foreach (var error in ModelState )
                    {
                        ModelState.AddModelError("", error+"");
                    }
                ViewBag.idcat = _reBook.category();
                return View(obj);

            }
          
        }


        [HttpGet]
        public ActionResult editbook(int id)
        {
            var item = _reBook.get<book>(id);
            ViewBag.idcat = _reBook.category();
            if (item != null)
            {
                return View(item);
            }
            return RedirectToAction("Error");
            
        }

        [HttpPost]
        public ActionResult editbook(book obj)
        {
            if (ModelState.IsValid)
            {
                _reBook.edit(obj);
                return RedirectToAction("listbook");
            }

            ViewBag.idcat = _reBook.category();

            return View(obj);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>


        [HttpGet]
        public ActionResult listCategory()
        {
            IEnumerable<category> item = _reCategory.list<category>()  ;
            return View(item);
        }

        [HttpGet]
        public ActionResult AddCategory()
        {
           
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(category obj)
        {
            if (ModelState.IsValid)
            {
                _reCategory.add(obj);
                return RedirectToAction("listCategory");
            }

          
            return View(obj);
        }



        [HttpGet, HttpPost]
        public ActionResult DeleteCategory(int id)
        {
            _reCategory.delete(_reCategory.get<category>(id));
            return RedirectToAction("listCategory");
        }

         
        [HttpGet]
        public ActionResult editCategory(int id)
        {
            var item = _reCategory.get<category>(id);
            if (item != null)
            {
                return View(item);
            }
            return RedirectToAction("Error");
           
        }

        [HttpPost]
        public ActionResult editCategory(category obj)
        {
            if (ModelState.IsValid)
            {
                _reCategory.edit(obj);
                return RedirectToAction("listCategory");
            }


            return View(obj);
        }

      
        /// <summary>
        /// //////
        /// </summary>
        /// <returns></returns>

        [HttpGet]
        public ActionResult listBookAuthor()
        {
            IEnumerable<book_author> item = _reBookAuthor.list<book_author>();
            return View(item);
        }

        [HttpGet]
        public ActionResult AddBookAuthor()
        {
            ViewBag.idbook =   _reBookAuthor.books();
            ViewBag.idAuthor = _reBookAuthor.authoers();
            return View();
        }

        [HttpPost]
        public ActionResult AddBookAuthor(book_author obj)
        {
            if (ModelState.IsValid)
            {
                _reBookAuthor.add (obj);
                return RedirectToAction("listBookAuthor");
            }

            ViewBag.idbook = _reBookAuthor.books();
            ViewBag.idAuthor = _reBookAuthor.authoers();
            return View(obj);
        }



        [HttpGet, HttpPost]
        public ActionResult DeleteBookAuthor(int id)
        {
            _reBookAuthor.delete(_reBookAuthor.get<book_author>(id));
            return RedirectToAction("listBookAuthor");
        }


        [HttpGet]
        public ActionResult editBookAuthor(int id)
        {
            var item = _reBookAuthor.get<book_author>(id);
            ViewBag.idbook = _reBookAuthor.books();
            ViewBag.idAuthor = _reBookAuthor.authoers();

            if (item != null)
            {
                return View(item);
            }
            return RedirectToAction("Error");
            
        }

        [HttpPost]
        public ActionResult editBookAuthor(book_author obj)
        {
            if (ModelState.IsValid)
            {
                _reBookAuthor.edit(obj);
                return RedirectToAction("listBookAuthor");
            }
            ViewBag.idbook = _reBookAuthor.books();
            ViewBag.idAuthor = _reBookAuthor.authoers();
            return View(obj);
        }



        /// <summary>
        /// //////
        /// </summary>
        /// <returns></returns>


        [HttpGet]
        public ActionResult listAuthor()
        {
            IEnumerable<author> item = _reAuthoer.list<author>();
            return View(item);
        }

        [HttpGet]
        public ActionResult AddAuthor()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAuthor(author obj)
        {
            if (ModelState.IsValid)
            {
                _reAuthoer.add<author>(obj);
                return RedirectToAction("listAuthor");
            }

 
            return View(obj);
        }



        [HttpGet,HttpPost]
        public ActionResult DeleteAuthor(int id)
        {
            _reAuthoer.delete(_reAuthoer.get<author>(id));
            return RedirectToAction("listAuthor");
        }


        [HttpGet]
        public ActionResult editAuthor(int id)
        {
            var item = _reAuthoer.get<author>(id);
            if (item != null)
            {
                return View(item);
            }
            return RedirectToAction("Error");
        
        }

        [HttpPost]
        public ActionResult editAuthor(author obj)
        {
            if (ModelState.IsValid)
            {
                _reAuthoer.edit(obj);
                return RedirectToAction("listAuthor");
            }
   
            return View(obj);
        }



    }
}

Controllers/MemberController.cs
using Labrary2023.Data.Repository;
using Labrary2023.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Labrary2023.Controllers
{
    [Authorize]
    public class MemberController : Controller
    {
        private readonly Reposotorymember _rememper;
        private readonly Reposotorymember_state _rememperstate;
        private readonly Rreposotoryfine_payment _refinepay;
  
        public MemberController(Reposotorymember rememper , Reposotorymember_state rememperstate , Rreposotoryfine_payment refinepay)
        {
            _refinepay = refinepay;
            _rememper = rememper;
            _rememperstate = rememperstate;
        }

        public ActionResult Index()
        {
            return View();
        }
 
        /// <summary>
        /// //////////
        /// </summary>
        /// <returns></returns>

        [HttpGet]
        public ActionResult listmember()
        {
            IEnumerable<member>items = _rememper.list<member>();
            return View(items);
        }

        [HttpGet]
        public ActionResult Addmember() 
        {
            ViewBag.idmeb_sta = _rememper.member_statas();
            return View();
        }
       
        [HttpPost]
        public ActionResult Addmember(member obj)
        {
            if(ModelState.IsValid)
            {
                _rememper.add<member>(obj);
                return RedirectToAction("listmember");
            }
            ViewBag.idmeb_sta = _rememper.member_statas();

            return View(obj);
        }

 
        [HttpGet]
        public ActionResult editmember(int id)
        {
            var item = _rememper.get<member>(id);
            ViewBag.idmeb_sta = _rememper.member_statas();
            
            if(item != null)
            {
                return View(item);
            }
            return RedirectToAction("Error");
          
        }
        
        [HttpPost]
        public ActionResult editmember(member obj)
        {


            if(ModelState.IsValid)
            {
                _rememper.edit<member>(obj);
                return RedirectToAction("listmember");
            }
            ViewBag.idmeb_sta = _rememper.member_statas();
            return View(obj) ;
        }
         
        [HttpGet,HttpPost]
        public ActionResult Deletemember(int id)
        {
            _rememper.delete(_rememper.get<member>(id));
            return RedirectToAction("listmember");
        }

        /////////////////
        /////////////////
        /////////////////
     


        [HttpGet]
        public ActionResult listmemberstate()
        {
            IEnumerable<member_state> items =_rememperstate.list<member_state>();
            return View(items);
        }

        [HttpGet]
        public ActionResult addmemberstate()
        {
            return View();
        }
       
        [HttpPost]
        public ActionResult addmemberstate(member_state obj)
        {
            if(ModelState.IsValid)
            {
                _rememperstate.add(obj);
                return RedirectToAction("listmemberstate");
            }
            return View(obj);
        }
 
        [HttpGet]
        public ActionResult editmemberstate(int id)
        {
            var item = _rememperstate.get<member_state>(id);
            if (item != null)
            {
                return View(item);
            }
            return RedirectToAction("Error");
           
        }
        [HttpPost]
        public ActionResult editmemberstate(member obj)
        {
            if (ModelState.IsValid)
            {
                _rememperstate.edit(obj);
                return RedirectToAction("listmemberstate");
            }
            return View(obj);
            
        }

        [HttpGet, HttpPost]
        public ActionResult Deletememberstate(int id)
        {
            _rememperstate.delete<member_state>(_rememperstate.get<member_state>(id));
            return View();
        }

        /////////////////
        /////////////////
        /////////////////

        [HttpGet]
        public ActionResult listfine_payment()
        {
            IEnumerable<fine_payment> items = _refinepay.list<fine_payment>();
            return View(items);
        }

        [HttpGet]
        public ActionResult addfine_payment()
        {
            ViewBag.idmeb = _refinepay.members();
            return View();
        }

        [HttpPost]
        public ActionResult addfine_payment(fine_payment obj)
        {
            if (ModelState.IsValid)
            {
                _refinepay.add(obj);
                return RedirectToAction("listfine_payment");
            }
            ViewBag.idmeb = _refinepay.members();

            return View(obj);
        }

        [HttpGet]
        public ActionResult editfine_payment(int id)
        {
            var item = _refinepay.get<fine_payment>(id);
            ViewBag.idmeb = _refinepay.members();

            if (item != null)
            {
                return View(item);
            }

            return RedirectToAction("Error");

        }
     
        [HttpPost]
        public ActionResult editfine_payment(fine_payment obj)
        {
            if (ModelState.IsValid)
            {
                _refinepay.edit(obj);
                return RedirectToAction("listfine_payment");
            }
            ViewBag.idmeb = _refinepay.members();

            return View(obj);

        }

        [HttpGet, HttpPost]
        public ActionResult Deletefine_payment(int id)
        {
            _refinepay.delete<fine_payment>(_refinepay.get<fine_payment>(id));
            return   RedirectToAction("listfine_payment");
        }



    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Labrary </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Labrary2023.styles.css" asp-append-version="true" />
</head>
<body >
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Labrary2023</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>  
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Index">Member</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Payments" asp-action="Index">Payments</a>
                        </li>
                    </ul>
                    @if (signInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav">

                            <li>
                                <form method="post" asp-controller="Account" asp-action="logout">

                                    <button type="submit" class="nav-link btn btn-link py-0">
                                        logout <span>@User.Identity.Name</span>
                                    </button>

                                </form>
                            </li>
                        </ul>
                    }

                    else
                    {
                        <ul class="navbar-nav">

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-action="Login" asp-controller="Account">login</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link text-dark" asp-action="Register" asp-controller="Account">Register</a>
                            </li>
                        </ul>
                    }

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Labrary2023 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>