Controllers/PaymentsController.cs
using Labrary2023.Data.Repository;
using Labrary2023.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Labrary2023.Controllers
{
    [Authorize]
    public class PaymentsController : Controller
    {
        public readonly Reposotoryloan _reloan;
        public readonly Reposotoryreservation _reRes;
        public readonly Reposotoryreservation_state _reResSta;
        public readonly Reposotoryfine _refine;

        public PaymentsController(Reposotoryloan reloan , Reposotoryreservation reRes , Reposotoryreservation_state reResSta , Reposotoryfine refine)
        {
            _refine = refine;
            _reloan = reloan;
            _reRes = reRes;
            _reResSta = reResSta;
        }
        public ActionResult Index()
        {
            return View();
        }




        [HttpGet]
        public ActionResult listreservationstate()
        {
            IEnumerable<reservation_state> items = _reResSta.list<reservation_state>();

            return View(items);
        }

        [HttpGet]
        public ActionResult addreservationstate()
        {
        
            return View();
        }

        [HttpPost]
        public ActionResult addreservationstate(reservation_state obj)
        {
            if (ModelState.IsValid)
            {
                _reResSta.add(obj);
                return RedirectToAction("listreservationstate");
            }
           
            return View(obj);
        }

        [HttpGet]
        public ActionResult editreservationstate(int id)
        {
            var item = _reResSta.get<reservation_state>(id);

            if (item != null)
            {
               
                return View(item);

            }
            return RedirectToAction("Error");

        }

        [HttpPost]
        public ActionResult editreservationstate(reservation_state obj)
        {
            if (ModelState.IsValid)
            {
                _reResSta.edit(obj);
                return RedirectToAction("listreservationstate");
            }
           
            return View(obj);
        }


        [HttpGet, HttpPost]
        public ActionResult deletereservationstate(int id)
        {
            _reResSta.delete(_reResSta.get<reservation_state>(id));

            return RedirectToAction("listreservationstate");

        }

         

        /// <summary>
        /// /////////
        /// </summary>
        /// <returns></returns>
      
        
        [HttpGet]
        public ActionResult listreservation()
        {
            IEnumerable<reservation> items = _reRes.list<reservation>();
            return View(items);
        }

        [HttpGet]
        public ActionResult addreservation()
        {
            ViewBag.idmeb = _reRes.members();
            ViewBag.idbook = _reRes.books();
            ViewBag.reservation_states_id = _reRes.reservation_status();
            return View();
        }

        [HttpPost]
        public ActionResult addreservation(reservation obj )
        {
            if(ModelState.IsValid)
            {
                _reRes.add(obj);
                return RedirectToAction("listreservation");
            }
            ViewBag.idmeb = _reRes.members();
            ViewBag.idbook = _reRes.books();
            ViewBag.reservation_states_id = _reRes.reservation_status();
            return View(obj);
        }

        [HttpGet]
        public ActionResult editreservation(int id)
        {
            var item = _reRes.get<reservation>(id);

            if(item != null)
            {
                ViewBag.idmeb = _reRes.members();
                ViewBag.idbook = _reRes.books();
                ViewBag.reservation_states_id = _reRes.reservation_status();
                return View(item);

            }
            return RedirectToAction("Error");

        }

        [HttpPost]
        public ActionResult editreservation(reservation obj)
        {
            if (ModelState.IsValid)
            {
                _reRes.edit(obj);
                return RedirectToAction("listreservation");
            }
            ViewBag.idmeb = _reRes.members();
            ViewBag.idbook = _reRes.books();
            ViewBag.reservation_states_id = _reRes.reservation_status();
            return View(obj);
        }


        [HttpGet,HttpPost]
        public ActionResult deletereservation(int id)
        {
             _reRes.delete(_reRes.get<reservation>(id));

            return RedirectToAction("listreservation");

        }



        /// <summary>
        /// /////////
        /// </summary>
        /// <returns></returns>
        /// 


        [HttpGet]
        public ActionResult listloan()
        {
            IEnumerable<loan> items = _reloan.list<loan>();

            return View(items);
        }

        [HttpGet]
        public ActionResult addloan()
        {
            ViewBag.idmeb = _reloan.members();
            ViewBag.idbook = _reloan.books();
            return View();
        }

        [HttpPost]
        public ActionResult addloan(loan obj)
        {
            if (ModelState.IsValid)
            {
                _reloan.add(obj);
                return RedirectToAction("listloan");
            }
            ViewBag.idmeb = _reloan.members();
            ViewBag.idbook = _reloan.books();
            return View(obj);
        }

        [HttpGet]
        public ActionResult editloan(int id)
        {
            var item = _reloan.get<loan>(id);

            if (item != null)
            {
                ViewBag.idmeb = _reloan.members();
                ViewBag.idbook = _reloan.books();
                return View(item);

            }
            return RedirectToAction("Error");

        }

        [HttpPost]
        public ActionResult editloan(loan obj)
        {
            if (ModelState.IsValid)
            {
                _reloan.edit(obj);
                return RedirectToAction("listloan");
            }
            ViewBag.idmeb = _reloan.members();
            ViewBag.idbook = _reloan.books();
            return View(obj);
        }


        [HttpGet, HttpPost]
        public ActionResult deleteloan(int id)
        {
            _reloan.delete(_reloan.get<loan>(id));

            return RedirectToAction("listloan");

        }



        /// <summary>
        /// /////////
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult listfine()
        {
            IEnumerable<fine> items = _refine.list<fine>();

            return View(items);
        }

        [HttpGet]
        public ActionResult addfine()
        {
            ViewBag.idlon = _refine.Loans();
            return View();
        }

        [HttpPost]
        public ActionResult addfine(fine obj)
        {
            if (ModelState.IsValid)
            {
                _refine.add(obj);
                return RedirectToAction("listfine");
            }
            ViewBag.idlon = _refine.Loans();
            return View(obj);
        }

        [HttpGet]
        public ActionResult editfine(int id)
        {
            var item = _refine.get<fine>(id);

            if (item != null)
            {
                ViewBag.idlon = _refine.Loans();

                return View(item);

            }
            return RedirectToAction("Error");

        }

        [HttpPost]
       
        public ActionResult editfine(fine obj)
        {
            if (ModelState.IsValid)
            {
                _refine.edit(obj);
                return RedirectToAction("listfine");
            }
            ViewBag.idlon = _refine.Loans();

            return View(obj);
        }


        [HttpGet, HttpPost]
        public ActionResult deletefine(int id)
        {
            _refine.delete(_refine.get<fine>(id));

            return RedirectToAction("listfine");

        }








    }
}

Views/Payments/Index.cshtml
<a class="btn btn-primary" asp-controller="Payments" asp-action="addreservationstate">add reservation state </a>
<a class="btn btn-primary" asp-controller="Payments" asp-action="listreservationstate">list reservation state</a>

<a class="btn btn-primary" asp-controller="Payments" asp-action="addreservation">  add reservation</a>
<a class="btn btn-primary" asp-controller="Payments" asp-action="listreservation"> list reservation</a>

<a class="btn btn-primary" asp-controller="Payments" asp-action="addloan">add loan</a>
<a class="btn btn-primary" asp-controller="Payments" asp-action="listloan">list loan</a>

<a class="btn btn-primary" asp-controller="Payments" asp-action="addfine">add fine</a>
<a class="btn btn-primary" asp-controller="Payments" asp-action="listfine">list  fine  </a>

Views/Payments/addfine.cshtml
@model Labrary2023.Models.fine

@{
    ViewData["Title"] = "addfine";
}

<h1>addfine</h1>

<h4>fine</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="addfine">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="idlon" class="control-label"></label>
                <select asp-for="idlon" class ="form-control" asp-items="ViewBag.idlon"></select>
            </div>
            <div class="form-group">
                <label asp-for="fine_Date" class="control-label"></label>
                <input asp-for="fine_Date" class="form-control" />
                <span asp-validation-for="fine_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fine_amount" class="control-label"></label>
                <input asp-for="fine_amount" class="form-control" />
                <span asp-validation-for="fine_amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
 

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Payments/addloan.cshtml
@model Labrary2023.Models.loan

@{
    ViewData["Title"] = "addloan";
}

<h1>addloan</h1>

<h4>loan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="addloan">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="idbook" class="control-label"></label>
                <select asp-for="idbook" class ="form-control" asp-items="ViewBag.idbook"></select>
            </div>
            <div class="form-group">
                <label asp-for="idmeb" class="control-label"></label>
                <select asp-for="idmeb" class ="form-control" asp-items="ViewBag.idmeb"></select>
            </div>
            <div class="form-group">
                <label asp-for="loan_date" class="control-label"></label>
                <input asp-for="loan_date" class="form-control" />
                <span asp-validation-for="loan_date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="return_date" class="control-label"></label>
                <input asp-for="return_date" class="form-control" />
                <span asp-validation-for="return_date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

 
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Payments/addreservation.cshtml
@model Labrary2023.Models.reservation

@{
    ViewData["Title"] = "addreservation";
}

<h1>addreservation</h1>

<h4>reservation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="addreservation">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="idbook" class="control-label"></label>
                <select asp-for="idbook" class ="form-control" asp-items="ViewBag.idbook"></select>
            </div>
            <div class="form-group">
                <label asp-for="idmeb" class="control-label"></label>
                <select asp-for="idmeb" class ="form-control" asp-items="ViewBag.idmeb"></select>
            </div>
            <div class="form-group">
                <label asp-for="reservation_states_id" class="control-label"></label>
                <select asp-for="reservation_states_id" class ="form-control" asp-items="ViewBag.reservation_states_id"></select>
            </div>
            <div class="form-group">
                <label asp-for="reservation_date" class="control-label"></label>
                <input asp-for="reservation_date" class="form-control" />
                <span asp-validation-for="reservation_date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
 

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Payments/addreservationstate.cshtml
@model Labrary2023.Models.reservation_state

@{
    ViewData["Title"] = "addreservationstate";
}

<h1>addreservationstate</h1>

<h4>reservation_state</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="addreservationstate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="value_state" class="control-label"></label>
                <input asp-for="value_state" class="form-control" />
                <span asp-validation-for="value_state" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

 

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Payments/editfine.cshtml
@model Labrary2023.Models.fine

@{
    ViewData["Title"] = "editfine";
}

<h1>editfine</h1>

<h4>fine</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="editfine">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="idfn" />
            <div class="form-group">
                <label asp-for="idlon" class="control-label"></label>
                <select asp-for="idlon" class="form-control" asp-items="ViewBag.idlon"></select>
                <span asp-validation-for="idlon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fine_Date" class="control-label"></label>
                <input asp-for="fine_Date" class="form-control" />
                <span asp-validation-for="fine_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fine_amount" class="control-label"></label>
                <input asp-for="fine_amount" class="form-control" />
                <span asp-validation-for="fine_amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

 
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Payments/editloan.cshtml
@model Labrary2023.Models.loan

@{
    ViewData["Title"] = "editloan";
}

<h1>editloan</h1>

<h4>loan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="editloan">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="idlo" />
            <div class="form-group">
                <label asp-for="idbook" class="control-label"></label>
                <select asp-for="idbook" class="form-control" asp-items="ViewBag.idbook"></select>
                <span asp-validation-for="idbook" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="idmeb" class="control-label"></label>
                <select asp-for="idmeb" class="form-control" asp-items="ViewBag.idmeb"></select>
                <span asp-validation-for="idmeb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="loan_date" class="control-label"></label>
                <input asp-for="loan_date" class="form-control" />
                <span asp-validation-for="loan_date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="return_date" class="control-label"></label>
                <input asp-for="return_date" class="form-control" />
                <span asp-validation-for="return_date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
 

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Payments/editreservation.cshtml
@model Labrary2023.Models.reservation

@{
    ViewData["Title"] = "editreservation";
}

<h1>editreservation</h1>

<h4>reservation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="editreservation">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="idres" />
            <div class="form-group">
                <label asp-for="idbook" class="control-label"></label>
                <select asp-for="idbook" class="form-control" asp-items="ViewBag.idbook"></select>
                <span asp-validation-for="idbook" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="idmeb" class="control-label"></label>
                <select asp-for="idmeb" class="form-control" asp-items="ViewBag.idmeb"></select>
                <span asp-validation-for="idmeb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="reservation_states_id" class="control-label"></label>
                <select asp-for="reservation_states_id" class="form-control" asp-items="ViewBag.reservation_states_id"></select>
                <span asp-validation-for="reservation_states_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="reservation_date" class="control-label"></label>
                <input asp-for="reservation_date" class="form-control" />
                <span asp-validation-for="reservation_date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
 

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Payments/editreservationstate.cshtml
@model Labrary2023.Models.reservation_state

@{
    ViewData["Title"] = "editreservationstate";
}

<h1>editreservationstate</h1>

<h4>reservation_state</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="editreservationstate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="idres_sta" />
            <div class="form-group">
                <label asp-for="value_state" class="control-label"></label>
                <input asp-for="value_state" class="form-control" />
                <span asp-validation-for="value_state" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Payments/listfine.cshtml
@model IEnumerable<Labrary2023.Models.fine>

@{
    ViewData["Title"] = "listfine";
}

<h1>listfine</h1>
 
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.fine_Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fine_amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Loan)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.fine_Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fine_amount)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Loan.Member.Fname)
            </td>
            <td>
                    <a asp-action="editfine" asp-route-id="@item.idfn">Edit</a> |
          
                    <a asp-action="deletefine" asp-route-id="@item.idfn">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Payments/listloan.cshtml
@model IEnumerable<Labrary2023.Models.loan>

@{
    ViewData["Title"] = "listloan";
}

<h1>listloan</h1>
 
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.loan_date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.return_date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Book)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Member)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.loan_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.return_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Book.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Member.Fname)
            </td>
            <td>
                    <a asp-action="editloan" asp-route-id="@item.idlo">Edit</a> |

                    <a asp-action="deleteloan" asp-route-id="@item.idlo">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Payments/listreservation.cshtml
@model IEnumerable<Labrary2023.Models.reservation>

@{
    ViewData["Title"] = "listreservation";
}

<h1>listreservation</h1>

 
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.reservation_date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Book)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Member)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.reservation_states)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.reservation_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Book.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Member.Fname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.reservation_states.value_state)
            </td>
            <td>
                    <a asp-action="editreservation" asp-route-id="@item.idres">Edit</a> |
                 
                    <a asp-action="deletereservation" asp-route-id="@item.idres">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Payments/listreservationstate.cshtml
@model IEnumerable<Labrary2023.Models.reservation_state>

@{
    ViewData["Title"] = "listreservationstate";
}

<h1>listreservationstate</h1>

 
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.value_state)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.value_state)
            </td>
            <td>
                <a asp-action="editreservationstate" asp-route-id="@item.idres_sta">Edit</a> |
               
                <a asp-action="deletereservationstate" asp-route-id="@item.idres_sta">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>